# Generated by Django 5.0.4 on 2024-05-03 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
